# Generated by Django 4.2.5 on 2023-10-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
